---
# tasks file for nfs

-   name: Ensure NFS tools are installed
    apt:
        update_cache: yes
        state: present
        name: "{{ nfs_packages }}"
    become: true

-   name: Manage exports
    template:
        src: exports.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: 0644
    become: true
    notify: reload nfs

-   name: Ensure nfs daemon is running
    service:
        name: nfs-kernel-server
        enabled: yes
        state: started
    become: true
        
